### ISSUE TITLE
Icons on abilities being set to default when moved to a character sheet.

### ISSUE THREAD

**Issue by avorial** [3darkman/foundryvtt-chroniclesystem#22]
For example. 

If you change the Marksmanship icon, and then drag it to a new character. The text & specialties all move to the ability on the new character. The icon you changed does not. 

<img width="982" alt="chrome_2022-05-20_08-11-47" src="https://user-images.githubusercontent.com/65983414/169558326-ee812ac4-4ccf-4afc-80e0-0590877d355d.png">

**Comment by 3darkman** [comment]
this has already been fixed in the v10_update branch, so it will be available in the next system version.

tks for report.

**Comment by 3darkman** [comment]
resolved in version 0.4.0
