### ISSUE TITLE
Dragging/Placing Characters in to House Sheets is broken

### ISSUE THREAD

**Issue by avorial** [3darkman/foundryvtt-chroniclesystem#29]
I tried to add a new head of house to a sheet, and you can not add them anymore. Ones you already had added still work. But you lose the ability to do it now. 

Troubleshooting tried. 

1. I made a new house sheet and tried it (No change)
2. I made a new character sheet and tried it (No change)
3. Tried placing in Items (instead of actors) that seems to still work fine.

**Comment by jesuisfrog** [comment]
I believe that's part of the V10 fixes I've seen in 3darkman's v10 branch

**Comment by 3darkman** [comment]
resolved in version 0.4.0
