### ISSUE TITLE
Issue with adding members to the House sheet. 

### ISSUE THREAD

**Issue by jesuisfrog** [3darkman/foundryvtt-chroniclesystem#33]
After the new update, I've been populating a house sheet and I've so far encountered two issues:

1. Selecting "Steward" will not add the character to the sheet. It doesn't throw any errors, it just won't show up.
2. Trying to delete the current "Head of House" throws an error. 

![image](https://user-images.githubusercontent.com/7178778/194784113-7bca4d2d-7dd7-4255-b5a6-03c3a208cff2.png)

**Comment by 3darkman** [comment]
ow... sorry for this... i'm fixing now.

**Comment by 3darkman** [comment]
can you check if stewart is not there in the home tab? because mine was added normally, it just doesn't appear in the members tab

**Comment by 3darkman** [comment]
![image](https://user-images.githubusercontent.com/20743586/194784645-63836e38-4907-4947-a2a8-a45b2acb6c18.png)

**Comment by jesuisfrog** [comment]
Oh ! I was on the members tab, didn't realize it was going to pop on the resources one 😄

**Comment by 3darkman** [comment]
bug fixed and available in version 0.4.1
