### ISSUE TITLE
Issue for "Combat and Intrigue" tab

### ISSUE THREAD

**Issue by jesuisfrog** [3darkman/foundryvtt-chroniclesystem#35]
It looks like none of the input boxes on the "Combat and Intrigue" tab are retaining information or even acknowledging values as the numbers do not update and the boxes will reset to 0 after closing the sheet. 

I'm referring to the following sections: 

- Intrigue Defense modifier
- Composure, both "Current" and modifier boxes
- Combat Defense modifier
- Health, both "Current" and modifier boxes

![image](https://user-images.githubusercontent.com/7178778/194974410-4d9da8b5-13f6-486b-ae76-a76f8979a6d3.png)

**Comment by 3darkman** [comment]
fixed in 0.4.2 release.
