### ISSUE TITLE
Roll Options

### ISSUE THREAD

**Issue by RomKre** [3darkman/foundryvtt-chroniclesystem#36]
There are several automations missing, but thats ok :)

The only problem is, that you often have to add bonus dices (ex. weapi grades) or modifiers, but there is now way to edit the roll before throwing the dices.

Maybe you could do a small dialog/box after clicking inside the sheet, to add a modifier or bonus dices?

**Comment by TitanicViking** [comment]
In my opinion this would be the biggest improvement to the system, as modifier prompts are pretty standard for most foundry systems.

**Comment by 3darkman** [comment]
implemented on commit dee0ddda2e3e41f8f27029fdfa604db2d3763011, will be available in the next version. 

Instruction: basically to open the roll modification window, just hold the ctrl key while clicking on the move.

**Comment by TitanicViking** [comment]
> implemented on commit [dee0ddd](https://github.com/3darkman/foundryvtt-chroniclesystem/commit/dee0ddda2e3e41f8f27029fdfa604db2d3763011), will be available in the next version.
> 
> Instruction: basically to open the roll modification window, just hold the ctrl key while clicking on the move.

Would it be possible to make this an option to toggle in system settings? For most, the prompt popping up automatically upon clicking an item would be more intuitive.

**Comment by 3darkman** [comment]
as a player at other tables in the foundry, I don't really agree with this, as it implies that most of the time you will need to modify your move or simply press an extra button.

however, since you like that format, it doesn't hurt to put an option in the settings.

**Comment by RomKre** [comment]
the system I use most often solved it with shift-click.

Single leftclick: With roll modifier dialog
Shift-Leftclick: Without

**Comment by 3darkman** [comment]
added in the settings, the player, not the master (although he can also configure it for his own machine), chooses whether he needs to hold ctrl or not to show the modifier window.

**Comment by 3darkman** [comment]
changed to Shift key

**Comment by 3darkman** [comment]
released in 0.5.0 version.
