### ISSUE TITLE
Automate Initiative 

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#37]
So at present when rolling initiative, you have to manually input it into the tracker, which takes a while. 

Perhaps some sort of macro or connection to the agility/quickness tests could be set up for this?

**Comment by 3darkman** [comment]
implemented in commit e3b6c262cd67e692bd8d71d711f5563148237165, will be available in the next release. Includes initiative for each type and encounter (combat, intrigue, and warfare)

**Comment by 3darkman** [comment]
released in 0.5.0 version.
