### ISSUE TITLE
Holdings with No Value Invisible on House Sheet

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#45]
I've noticed when you drag a holding onto the house sheet, if it has no investment rating it simply doesnt pop up on the sheet. Could we make it so even 0 cost holdings pop up? Otherwise you have to drag on other holdings just to get the menu to pop up.

**Comment by 3darkman** [comment]
fixed in commit f0816ab7bc86c0a79b31e9d2c04859f84f399366, will be available in the next version.

**Comment by tbsvttr** [comment]
Hi. Thanks for your work on this cool Foundry integration. Can you please do this release ASAP or provide a manifest url to your develop? Thanks a lot in advance.

**Comment by 3darkman** [comment]
available in release 0.6.0
