### ISSUE TITLE
Mod For Steward Missing on Holdings

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#46]
So there is a space in the steward section of the house that has a mod from holdings, but I cant find a place in the holdings entries to add this mod from. My players have a port that should add a +5 to this spot, but I dont see a way to add this currently.

**Comment by YolloDwarf** [comment]
#52 I tackled it in this PR, hopefully it will get approved

**Comment by TitanicViking** [comment]
Nice! Thanks for your help on this!

**Comment by 3darkman** [comment]
@YolloDwarf PR is merged. This will be available in version 0.6.0.
