### ISSUE TITLE
Qualities on Armor Bugged

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#47]
Was going to add the Clothing qualities from Masques & Marionettes onto armor entries. Noticed the quality button doesnt add a blank spot for anything on the armor items like it does on weapon entries.

**Comment by avorial** [comment]
Even if not used for M&M, an official SC book uses armor qualities so they should be added. (This is from Spark to Power)
![Acrobat_zLVmKxaBrL](https://user-images.githubusercontent.com/65983414/236874852-499d66ec-a0f0-4be7-ae5b-2e367e24cb88.png)

**Comment by 3darkman** [comment]
fixed in commit: 94202cf, will be available in the next version.

**Comment by 3darkman** [comment]
available in release 0.6.0
