### ISSUE TITLE
Quality of Life Suggestion - Stretch Description Boxes on Items

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#48]
So right now, the way alot of the system works with items & such is that the description box is a static size, which makes it so you have to scroll down & read a very narrow box. It would be a tremendous quality of life improvement if we could make it scale with the size of the window. 

Attaching image to show how it looks currently, & the entry for things like poisons takes up alot of that space, & would be easier to read if the bounding box stretched with the size of the item window. 
![image](https://user-images.githubusercontent.com/118582486/206583891-3b78810b-c3c5-41df-9b42-10c46554b7f7.png)

**Comment by 3darkman** [comment]
fixed in commit: a3cbb79, will be available in the next version.

**Comment by 3darkman** [comment]
available in release 0.6.0
