### ISSUE TITLE
Add DR rating to Intrigue Dispositions on Character Sheet

### ISSUE THREAD

**Issue by TitanicViking** [3darkman/foundryvtt-chroniclesystem#49]
On the current disposition setting on the intrigue tab it has the deception & persuasion modifiers, but its missing the associated DR rating for each disposition. 

Adding that would make it way easier to run intrigues, as without it we still have to reference all the dispositions manually to check the DR rating for each one.

**Comment by 3darkman** [comment]
fixed in commit: ff7752e, will be available in the next version.

**Comment by 3darkman** [comment]
available in release 0.6.0
