### ISSUE TITLE
You can not put 2 of the exact same weapon to represent one in each hand.

### ISSUE THREAD

**Issue by avorial** [3darkman/foundryvtt-chroniclesystem#59]
Any placement of the exact same weapon has no effect, if there is a problem with putting the exact same, maybe we can have left hand/right hand/two handed/two weapons?

**Comment by 3darkman** [comment]
fixed in commit: https://github.com/3darkman/foundryvtt-chroniclesystem/commit/41959145bde89ce15fce830447f7fd4fb51a0715, will be available in the next version.

**Comment by 3darkman** [comment]
available in release 0.6.0
