### ISSUE TITLE
Character sheet not populated with abilities and other tabs not editable.

### ISSUE THREAD

**Issue by Crazymajor** [3darkman/foundryvtt-chroniclesystem#71]
Abilities tab has no abilities listed and tabs like qualities don't have an edit button to add qualities. 

Foundry is up to date. Downloaded the system through multiple ways (manually through github and also through foundry) and same results found for both. No other modules being used. Foundry is being run locally on my system and not on a server.

![Abilities](https://github.com/3darkman/foundryvtt-chroniclesystem/assets/162837656/7b18a773-45d1-4562-ac72-bb355f41844e)
![Qualities](https://github.com/3darkman/foundryvtt-chroniclesystem/assets/162837656/acfd6db6-c84c-47c4-9ee9-59128e271eb7)

**Comment by 3darkman** [comment]
Everything needs to be created as an item and dragged to the character sheet... Take a look at the project readme for more clarification

**Comment by Crazymajor** [comment]
Ok I understand now. I didnt see anything in the readme about needing to create items for everything
